#!/usr/bin/env python3
"""
中文到英文页面名的映射字典
用于修复中文链接指向正确的英文分类页
"""

# 中文到英文页面名的映射
CHINESE_TO_ENGLISH = {
    # ===== 主题 (Topics) =====
    '电磁暂态仿真': 'emt-mathematical-foundation',
    '电磁暂态分析': 'emt-mathematical-foundation',
    '电磁暂态': 'emt-mathematical-foundation',
    'emt仿真': 'emt-mathematical-foundation',
    '频率相关建模': 'frequency-dependent-modeling',
    '频率相关模型': 'frequency-dependent-modeling',
    '频域建模': 'frequency-dependent-modeling',
    '并行计算': 'parallel-computing',
    '并行仿真': 'parallel-computing',
    '计算效率优化': 'parallel-computing',
    '实时仿真': 'real-time-simulation',
    '超实时仿真': 'real-time-simulation',
    '硬件在环': 'hil-simulation',
    '硬件在环仿真': 'hil-simulation',
    'hil仿真': 'hil-simulation',
    '混合仿真': 'co-simulation',
    '协同仿真': 'co-simulation',
    '机电-电磁暂态混合仿真': 'electromechanical-electromagnetic-hybrid-simulation',
    '机电-电磁混合仿真': 'electromechanical-electromagnetic-hybrid-simulation',
    '机电电磁混合仿真': 'electromechanical-electromagnetic-hybrid-simulation',
    '网络等值': 'network-equivalent',
    '等值建模': 'network-equivalent',
    '等效建模': 'network-equivalent',
    '动态相量法': 'dynamic-phasor',
    '动态相量建模': 'dynamic-phasor',
    '相量法': 'dynamic-phasor',
    '多速率仿真': 'multirate-method',
    '多速率方法': 'multirate-method',
    '变速率仿真': 'multirate-method',
    '谐波分析': 'harmonic-analysis',
    '谐波分析方法': 'harmonic-analysis-methods',
    '风电场': 'wind-farm-modeling',
    '风电场建模': 'wind-farm-modeling',
    '风电机组建模': 'wind-farm-modeling',
    '输电线路': 'transmission-line-modeling',
    '输电线路建模': 'transmission-line-modeling',
    '架空输电线路': 'transmission-line-modeling',
    '架空线路': 'transmission-line-modeling',
    '电缆': 'cable-modeling',
    '电缆建模': 'cable-modeling',
    '地下电缆': 'cable-modeling',
    '大规模电网仿真': 'large-scale-grid-simulation',
    '大电网仿真': 'large-scale-grid-simulation',
    '系统级仿真': 'large-scale-grid-simulation',
    '开关暂态': 'switching-transient',
    '开关建模': 'switch-modeling',
    '雷电过电压': 'lightning-overvoltage',
    '接地、防雷与过电压': 'grounding-lightning-overvoltage',
    '铁磁谐振': 'ferroresonance',
    '宽频振荡与稳定性分析': 'wideband-oscillation-stability',
    '宽频建模方法': 'wideband-modeling',
    '变压器': 'transformer-modeling',
    '变压器建模': 'transformer-modeling',
    '电力变压器': 'transformer-modeling',
    '换流变压器': 'converter-transformer-model',
    '同步电机': 'synchronous-machine-model',
    '同步电机建模': 'synchronous-machine-model',
    '同步发电机': 'synchronous-machine-model',
    '旋转电机': 'rotating-machine-modeling',
    '旋转电机建模': 'rotating-machine-modeling',
    '感应电机': 'induction-machine-model',
    '异步电机': 'induction-machine-model',
    '双馈感应发电机': 'dfig-model',
    'dfig': 'dfig-model',
    '永磁同步电机': 'pmsm-model',
    'pmsm': 'pmsm-model',
    '负荷模型': 'load-modeling',
    '负荷建模': 'load-modeling',
    '负荷与分布式电源建模': 'load-and-dg-modeling',
    '微电网与配电网': 'microgrid-distribution-network',
    'vsc-hvdc': 'vsc-hvdc',
    '高压直流输电': 'vsc-hvdc',
    '柔性直流输电': 'vsc-hvdc',
    '多端直流电网': 'mtdc-model',
    'mtdc': 'mtdc-model',
    '交直流电网': 'hybrid-acdc-network',
    '线路换相换流器': 'lcc-model',
    'lcc': 'lcc-model',
    '直流输电线路': 'transmission-line-modeling',

    # ===== 方法 (Methods) =====
    '节点分析法': 'nodal-analysis',
    '节点分析': 'nodal-analysis',
    '节点导纳矩阵法': 'nodal-analysis',
    '修正节点分析': 'nodal-analysis',
    '改进增广节点分析法': 'nodal-analysis',
    'mana': 'nodal-analysis',
    '伴随电路法': 'nodal-analysis',
    '伴随电路': 'nodal-analysis',
    '状态空间法': 'state-space-method',
    '状态空间': 'state-space-method',
    '状态空间建模': 'state-space-method',
    '状态空间模型': 'state-space-method',
    '矢量拟合': 'vector-fitting',
    '矢量拟合法': 'vector-fitting',
    'vf': 'vector-fitting',
    '有理函数逼近': 'vector-fitting',
    '有理函数拟合': 'vector-fitting',
    '有理逼近': 'vector-fitting',
    '平均值模型': 'average-value-model',
    '平均值建模': 'average-value-model',
    'avm': 'average-value-model',
    '数值积分': 'numerical-integration',
    '数值积分方法': 'numerical-integration',
    '梯形积分法': 'numerical-integration',
    '后向欧拉法': 'numerical-integration',
    '离散化方法': 'discretization-methods',
    '模型降阶': 'model-order-reduction',
    '模型降阶方法': 'model-order-reduction',
    'mor': 'model-order-reduction',
    '无源性强制': 'passivity-enforcement',
    '无源性约束': 'passivity-enforcement',
    '恒导纳模型': 'fixed-admittance',
    '恒导纳开关模型': 'fixed-admittance',
    'adc模型': 'fixed-admittance',
    '插值方法': 'interpolation-method',
    '插值': 'interpolation-method',
    '迭代求解方法': 'iterative-solvers',
    '迭代求解': 'iterative-solvers',
    '稀疏矩阵求解': 'sparse-matrix-solver',
    '稀疏矩阵求解方法': 'sparse-matrix-solver',
    '开关函数法': 'switching-function-method',
    '开关函数': 'switching-function-method',
    '开关建模方法': 'switch-modeling',
    '戴维南-诺顿等效': 'thevenin-norton-equivalent',
    '诺顿等效': 'thevenin-norton-equivalent',
    '戴维南等效': 'thevenin-norton-equivalent',
    '戴维南等效电路': 'thevenin-norton-equivalent',
    '坐标变换': 'coordinate-transformation',
    'park变换': 'coordinate-transformation',
    'clarke变换': 'coordinate-transformation',
    '相模变换': 'modal-transformation',
    '模态分析': 'modal-analysis',
    '模态分解': 'modal-decomposition',
    '模态变换': 'modal-transformation',
    '小信号分析方法': 'small-signal-analysis',
    '小信号分析': 'small-signal-analysis',
    '参数辨识方法': 'parameter-identification',
    '参数辨识': 'parameter-identification',
    'prony分析': 'prony-analysis',
    'prony': 'prony-analysis',
    '故障分析方法': 'fault-analysis-methods',
    '故障分析': 'fault-analysis-methods',
    '刚性系统处理': 'stiff-system-handling',
    '数值稳定性': 'numerical-stability',
    '数值稳定性分析': 'numerical-stability',
    '数值振荡抑制': 'numerical-oscillation-suppression',
    '特征值分析': 'eigenvalue-analysis',
    '特征线法': 'characteristic-method',
    '数值拉普拉斯变换': 'numerical-laplace-transform',
    '有限元法': 'finite-element-method',
    '有限元法(fem)': 'finite-element-method',
    'fem': 'finite-element-method',
    'fpga实时仿真': 'fpga-real-time-simulation',
    'gpu加速仿真': 'gpu-accelerated-simulation',
    '网络解耦': 'network-partitioning',
    '网络分割': 'network-partitioning',
    '补偿法': 'compensation-method',
    '大时间步长仿真': 'large-timestep-simulation',

    # ===== 模型 (Models) =====
    'mmc': 'mmc-model',
    'mmc建模': 'mmc-model',
    '模块化多电平换流器': 'mmc-model',
    '模块化多电平换流器(mmc)建模': 'mmc-model',
    '半桥子模块': 'mmc-model',
    '全桥子模块': 'mmc-model',
    '子模块': 'mmc-model',
    'vsc': 'vsc-model',
    'vsc建模': 'vsc-model',
    '电压源换流器': 'vsc-model',
    '电压源换流器(vsc)': 'vsc-model',
    '电力电子变流器': 'vsc-model',
    '电力电子变换器': 'vsc-model',
    '换流器模型': 'vsc-model',
    '跟网型变流器': 'grid-following-inverter',
    'gfl': 'grid-following-inverter',
    '构网型变流器': 'grid-forming-inverter',
    'gfm': 'grid-forming-inverter',
    '虚拟同步机': 'grid-forming-inverter',
    'vsg': 'grid-forming-inverter',
    '混合ac/dc变流器': 'hybrid-acdc-converter',
    '储能变流器': 'energy-storage-converter',
    '电池储能系统': 'bess-model',
    'bess': 'bess-model',
    '光伏系统': 'pv-system-model',
    '光伏': 'pv-system-model',
    'pv系统': 'pv-system-model',
    '锁相环': 'pll-model',
    '锁相环(pll)': 'pll-model',
    'pll': 'pll-model',
    '矢量控制': 'vector-control-model',
    'pi/pid控制器': 'pi-controller-model',
    'pi控制器': 'pi-controller-model',
    'pid控制器': 'pi-controller-model',
    '下垂控制': 'droop-control-model',
    'pwm调制器': 'pwm-modulator-model',
    'pwm': 'pwm-modulator-model',
    'emi滤波器': 'emi-filter-model',
    'emc滤波器': 'emi-filter-model',
    '电压电流传感器': 'voltage-current-sensor-model',
    '电容': 'capacitor-model',
    '电感': 'inductor-model',
    '电阻': 'resistor-model',
    '电阻模型': 'resistor-model',
    '二极管': 'diode-model',
    'igbt': 'igbt-model',
    'igbt(绝缘栅双极晶体管)': 'igbit-model',
    '绝缘栅双极晶体管': 'igbt-model',
    '接地系统': 'grounding-system-model',
    '频变土壤模型': 'frequency-dependent-soil-model',
    '避雷器': 'surge-arrester-model',
    '断路器': 'circuit-breaker-model',
    '通用线路模型': 'universal-line-model',
    '通用线路模型(ulm)': 'universal-line-model',
    'ulm': 'universal-line-model',
    'bergeron线路模型': 'bergeron-line-model',
    '频变线路模型': 'frequency-dependent-line-model',
    '相域建模': 'phase-domain-modeling',
    '相域模型': 'phase-domain-model',
    '时域仿真': 'time-domain-simulation',
    '暂态稳定分析': 'transient-stability-analysis',
    '潮流计算': 'power-flow-calculation',
    '交流电网': 'ac-power-grid',
    '等效电路法': 'equivalent-circuit-method',
    '详细等效模型': 'detailed-equivalent-model',
    '频域分析': 'frequency-domain-analysis',
    '频域节点分析': 'frequency-domain-nodal-analysis',
    '频域阻抗': 'frequency-domain-impedance',
    '新能源并网': 'renewable-energy-integration',
    '牛顿-拉夫逊法': 'newton-raphson-method',

    # ===== 实体 (Entities) =====
    'pscad': 'pscad-emtdc',
    'pscad/emtdc': 'pscad-emtdc',
    'emtdc': 'pscad-emtdc',
    'emtp': 'emtp',
    'emtp-rv': 'emtp',
    'atp-emtp': 'atp-emtp',
    'atp': 'atp-emtp',
    'atpdraw': 'atp-emtp',
    'emtp-atp': 'atp-emtp',
    'rtds': 'rtds',
    'matlab': 'matlab-simulink',
    'matlab/simulink': 'matlab-simulink',
    'simulink': 'matlab-simulink',
    'simscape': 'matlab-simulink',
    'cloudpss': 'cloudpss',
    'adpss': 'adpss',
    'psmodel': 'psmodel',
    'ieee': 'ieee',
    'cigre': 'cigre',
    '清华': 'tsinghua-university',
    '清华大学': 'tsinghua-university',
    '中国电科院': 'china-epri',
    '蒙特利尔大学': 'polytechnique-montreal',
    '曼尼托巴大学': 'university-manitoba',
    '曼尼托巴水电': 'manitoba-hydro',
    'abb': 'abb',
    'siemens': 'siemens',
    'comsol': 'comsol',
    'ansys': 'ansys',
    'gole': 'gole',
    'mahseredjian': 'mahseredjian',
    'gustavsen': 'bjorn-gustavsen',
    'semlyen': 'adam-semlyen',

    # ===== 特殊/组合 =====
    '机电暂态仿真': 'electromechanical-simulation',
    '机电暂态建模': 'electromechanical-modeling',
    '系统级快速仿真': 'fast-system-simulation',
    '不平衡工况分析': 'unbalanced-analysis',
    '正负序分解法': 'sequence-component-method',
    '傅里叶级数展开': 'fourier-series',
    '代数表征法': 'algebraic-characterization',
    '直流侧rlc滤波器': 'dc-rlc-filter',
    'h-鲁棒控制': 'h-infinity-control',
    '混合灵敏度优化': 'mixed-sensitivity-optimization',
    '双闭环pi控制器': 'dual-loop-pi-controller',
    '广义特征根法': 'generalized-eigenvalue-method',
    '小扰动线性化': 'small-perturbation-linearization',
    'ieee-39节点系统': 'ieee-39-bus-system',

    # ===== 额外常见映射（从dry-run结果添加）=====
    # 注意：以下映射指向实际存在的页面
    '仿真加速': 'parallel-computing',  # 使用现有页面
    '电磁暂态仿真加速': 'parallel-computing',
    '电磁暂态建模': 'emt-mathematical-foundation',
    '有限元法(fem)': 'emt-mathematical-foundation',  # 暂时映射到数学基础
    '锁相环(pll)': 'pll-model',
    '多馈入直流系统': 'mtdc-model',
    '风力发电机': 'wind-farm-modeling',
    '电力电子变压器': 'pet-sst-model',
    '多尺度仿真': 'multirate-method',  # 使用多速率页面
    '递归卷积': 'transmission-line-modeling',  # 使用线路建模页面
    '离线仿真': 'emt-mathematical-foundation',
    '联合仿真': 'co-simulation',
    '频变参数建模': 'frequency-dependent-modeling',
    '等效电路建模': 'network-equivalent',
    '并网逆变器': 'gfl-inverter-model',
    '交直流混合电网': 'vsc-hvdc',
    '网络分区': 'network-equivalent',
    'fpga硬件实现': 'fpga-real-time-simulation',
    'fpga硬件加速': 'fpga-real-time-simulation',
    '多端直流系统': 'mtdc-model',
    '降阶建模': 'model-order-reduction',
    '开关暂态分析': 'switching-transient',
    '隐式梯形积分法': 'numerical-integration',
    '矩量法(mom)': 'emt-mathematical-foundation',
    '高频隔离变压器': 'transformer-modeling',
    'fpga并行计算': 'fpga-real-time-simulation',
    '变步长仿真': 'multirate-method',
    '稳定性分析': 'wideband-oscillation-stability',
    '时域变换法': 'dynamic-phasor',
    '双端口网络': 'fdne-model',
    '多端口网络': 'fdne-model',
    'n端口网络': 'fdne-model',
    '电磁场': 'emt-mathematical-foundation',
    '时域有限差分': 'emt-mathematical-foundation',
    '人工神经网络': 'parameter-identification',
    '系统辨识': 'parameter-identification',
    '模型验证': 'model-verification-benchmark',
    '参数估计': 'parameter-identification',
    '灵敏度分析': 'small-signal-analysis',
    '不确定性量化': 'parameter-identification',
    '蒙特卡洛模拟': 'parameter-identification',
    '拉丁超立方采样': 'parameter-identification',
    '代理模型': 'model-order-reduction',
    '克里金插值': 'parameter-identification',
    '高斯过程': 'parameter-identification',
    '多项式混沌展开': 'parameter-identification',
    'karhunen-loève展开': 'model-order-reduction',
    '奇异值分解': 'model-order-reduction',
    '本征正交分解': 'model-order-reduction',
    '动态模态分解': 'model-order-reduction',
    '谱分析': 'harmonic-analysis',
    '小波分析': 'harmonic-analysis',
    '短时傅里叶变换': 'harmonic-analysis',
    'wigner-ville分布': 'harmonic-analysis',
    '希尔伯特-黄变换': 'harmonic-analysis',
    '经验模态分解': 'harmonic-analysis',
    '变分模态分解': 'harmonic-analysis',
    # 以下映射指向现有页面或相关页面
    '频域阻抗预测': 'harmonic-analysis',
    '鲁棒控制': 'vector-control-model',
    '环流抑制控制器': 'mmc-model',
    '高频振荡分析': 'wideband-oscillation-stability',
    '时滞系统稳定性': 'wideband-oscillation-stability',
    '戴维南等效电源': 'thevenin-norton-equivalent',
    '振荡抑制策略': 'wideband-oscillation-stability',
    '阻抗建模': 'frequency-dependent-modeling',
    'emtp电磁暂态仿真': 'emtp',
    'emtp仿真': 'emtp',
    '频率扫描法': 'harmonic-analysis',
    '电磁暂态模型': 'emt-mathematical-foundation',
    '波传播特性': 'transmission-line-modeling',
    '动态平均值建模': 'average-value-model',
    '非线性电感': 'transformer-modeling',
    '牛顿迭代法': 'iterative-solvers',
    '网络方程求解': 'network-equation-solution',
    '平波电抗器': 'inductor-model',
    '状态空间实现': 'state-space-method',
    '状态变量法': 'state-space-method',
    'dc-dc变换器': 'vsc-model',
    '数模混合仿真': 'hil-simulation',
    '固定步长仿真': 'numerical-integration',
    'gpu并行计算': 'gpu-accelerated-simulation',
    'average-value-model': 'average-value-model',
    # 新增映射到现有页面
    '不平衡工况分析': 'unbalanced-fault-analysis',
    '正负序分解法': 'harmonic-analysis',
    '傅里叶级数展开': 'harmonic-analysis',
    '代数表征法': 'state-space-method',
    '交流电网': 'network-equivalent',
    '直流侧rlc滤波器': 'emi-filter-model',
    '系统级快速仿真': 'parallel-computing',
    '广义特征根法': 'state-space-method',
    '小扰动线性化': 'small-signal-analysis',
    'h-鲁棒控制': 'vector-control-model',
    '混合灵敏度优化': 'vector-control-model',
    '双闭环pi控制器': 'pi-controller-model',
    '锁相环-pll': 'pll-model',
    '改进增广节点分析法-mana': 'nodal-analysis',
    '通用线路模型-ulm': 'transmission-line-modeling',
    '有限元法-fem': 'emt-mathematical-foundation',
    # 新增映射
    '离散伴随支路等效': 'nodal-analysis',  # 映射到节点分析
    '灵活分组聚类': 'network-equivalent',  # 映射到网络等值
    '通用电气网络': 'network-equivalent',
    '开关网络': 'switching-transient',  # 映射到开关暂态
    '非线性分段线性元件': 'switch-modeling',  # 映射到开关建模
    '电容电感储能元件': 'companion-circuit',  # 映射到伴随电路
    '改进增广节点分析法(mana)': 'nodal-analysis',
    '通用线路模型(ulm)': 'transmission-line-modeling',
    # 新增中文映射（从lint结果添加）
    '混合求解架构': 'co-simulation',
    '开关网络处理': 'switching-transient',
    '网络等值技术': 'network-equivalent',
    '电磁暂态仿真技术': 'emt-mathematical-foundation',
    '机电暂态仿真技术': 'electromechanical-electromagnetic-hybrid-simulation',
    '机电-电磁混合仿真技术': 'electromechanical-electromagnetic-hybrid-simulation',
    '数模混合仿真技术': 'hil-simulation',
    '异构多时间尺度并行混合仿真技术': 'electromechanical-electromagnetic-hybrid-simulation',
    '大型线性方程组分块求解方法': 'sparse-matrix-solver',
    '特高压交直流输电系统': 'vsc-hvdc',
    '电压源换流器-vsc-柔性直流电网': 'vsc-hvdc',
    '大功率电力电子设备': 'power-electronic-device-modeling',
    # 继续添加
    '新能源机组': 'renewable-energy-units',
    '三相瞬时值模型': 'three-phase-instantaneous-model',
    '相量模型': 'phasor-model',
    '大型交直流混联电网仿真': 'large-scale-hybrid-acdc-simulation',
    '仿真工具现状与实用化': 'simulation-tools-status',
    '电力系统': 'power-system',
    '大电网': 'large-scale-grid',
    '仿真': 'simulation',
    '暂态': 'transient',
    '稳态': 'steady-state',
    '动态': 'dynamic',
    '控制': 'control',
    '保护': 'protection',
    '调度': 'dispatch',
    '运行': 'operation',
    '规划': 'planning',
    '设计': 'design',
    '分析': 'analysis',
    '计算': 'computation',
    '建模': 'modeling',
    '仿真技术': 'simulation-technology',
    '数字仿真': 'digital-simulation',
    '电磁暂态': 'electromagnetic-transient',
    '机电暂态': 'electromechanical-transient',
    '中长期动态': 'mid-long-term-dynamic',
    '小干扰稳定': 'small-signal-stability',
    '暂态稳定': 'transient-stability',
    '电压稳定': 'voltage-stability',
    '频率稳定': 'frequency-stability',
    '功角稳定': 'angle-stability',
}


def get_english_page(chinese_name):
    """获取中文名对应的英文页面名"""
    return CHINESE_TO_ENGLISH.get(chinese_name.lower().strip(), None)


def normalize_chinese_name(name):
    """标准化中文名（去除空格、统一大小写）"""
    return name.lower().strip().replace(' ', '')

# 最后一批中文映射
CHINESE_TO_ENGLISH.update({
    '电网调度生产应用': 'dispatch-operation',
    '宽频振荡与电压稳定分析': 'wideband-oscillation-stability',
    '时域公式化': 'time-domain-formulation',
    '贝杰龙模型': 'bergeron-model',
    '集中电阻近似': 'lumped-resistance-approximation',
    '平衡三相线路': 'balanced-three-phase-line',
    '分布参数线路': 'distributed-parameter-line',
    'electromagnetic-transient': 'emt-mathematical-foundation',
    '数字仿真器': 'digital-simulator',
    '多有源桥型电力电子变压器简化电磁暂态等效模型': 'pet-sst-model',
})

# 补充中文映射
CHINESE_TO_ENGLISH.update({
    '离线至实时仿真移植': 'real-time-simulation',
    '模型兼容层映射': 'model-compatibility-layer',
    '网表自动导入导出': 'netlist-import-export',
    '硬件在环联合仿真': 'hil-simulation',
    '数值阻尼优化': 'numerical-damping-optimization',
    '大规模电力系统': 'large-scale-power-system',
    '无功补偿装置': 'reactive-compensation-device',
    '继电保护与控制设备': 'protection-control-device',
    '用户自定义代码模型': 'user-defined-code-model',
    '离线仿真移植': 'offline-to-realtime-porting',
    '广域监测保护与控制': 'wide-area-monitoring-protection',
    '模型兼容性': 'model-compatibility',
    '傅里叶滤波': 'fourier-filtering',
    '对称分量法': 'symmetrical-components',
    '复数微分方程求解': 'complex-differential-equation-solving',
    '时域阻抗估计': 'time-domain-impedance-estimation',
})

# 补充中文映射 - 第二批
CHINESE_TO_ENGLISH.update({
    '序网模型': 'sequence-network-model',
    '数字距离保护': 'digital-distance-protection',
    '平行输电线路': 'parallel-transmission-line',
    '距离保护': 'distance-protection',
    '故障阻抗模型': 'fault-impedance-model',
    '等效故障回路': 'equivalent-fault-loop',
})

# 第三批映射 - 专业术语
CHINESE_TO_ENGLISH.update({
    'jmarti模型': 'universal-line-model',
    'bergeron-line-model': 'bergeron-model',
    'clarke模态变换': 'modal-transformation',
    '阻抗测量': 'impedance-measurement',
    '折叠线等效模型': 'folded-line-equivalent',
    '数字继电保护': 'digital-relay-protection',
    '平行线路保护': 'parallel-line-protection',
    '频域扫描': 'frequency-scan',
    '理想变压器等效电路': 'ideal-transformer-equivalent',
    '换位三相输电线路': 'transposed-three-phase-line',
    '高阻故障检测': 'high-impedance-fault-detection',
    '单相输电线路模型': 'single-phase-line-model',
    # 实体/工具映射
    'phasor-measurement-unit': 'phasor-measurement-unit',
    'pmu': 'phasor-measurement-unit',
    'state-estimation': 'state-estimation',
    'fault-analysis': 'fault-analysis-methods',
    'impedance-relay': 'distance-protection',
    'fixed-point-conversion': 'numerical-integration',
    'model-compatibility': 'model-compatibility-layer',
})

# 第四批映射 - 更多专业术语
CHINESE_TO_ENGLISH.update({
    'atp-emtp模型实现': 'atp-emtp',
    '谐波传递系数推导': 'harmonic-transfer-coefficient',
    '土壤频变特性': 'frequency-dependent-soil',
    '模态域解耦': 'modal-domain-decoupling',
    '交流耦合网络等效模型': 'ac-coupled-network-equivalent',
    '换流站-逆变器': 'converter-station-inverter',
    '关断角定量计算': 'extinction-angle-calculation',
    '电磁暂态仿真验证': 'emt-simulation-verification',
    '阻抗继电器': 'distance-protection',
    '状态估计': 'state-estimation',
    '故障分析': 'fault-analysis-methods',
    '定点转换': 'numerical-integration',
    '数字继电保护': 'digital-relay-protection',
    '折叠线等效': 'transmission-line-modeling',
    '理想变压器等效': 'transformer-modeling',
    '高阻故障检测': 'fault-analysis-methods',
    '单相线路模型': 'transmission-line-modeling',
    '换位三相线路': 'transmission-line-modeling',
    '平行线路保护': 'parallel-line-protection',
})

# 第五批映射
CHINESE_TO_ENGLISH.update({
    '谐波交互机制': 'harmonic-interaction',
    '并发换相失败': 'concurrent-commutation-failure',
    '分层接入': 'layered-connection',
    '交流故障暂态分析': 'ac-fault-transient-analysis',
    'state-space': 'state-space-method',
    'synchronous-machine': 'synchronous-machine-model',
    'model-compatibility': 'model-compatibility-layer',
    'digital-relay-protection': 'digital-relay-protection',
    'bergeron-line-model': 'bergeron-model',
    'folded-line-equivalent': 'transmission-line-modeling',
    'ideal-transformer-equivalent': 'transformer-modeling',
    'transposed-three-phase-line': 'transmission-line-modeling',
    'single-phase-line-model': 'transmission-line-modeling',
    '关断角计算': 'extinction-angle-calculation',
})

# 第六批 - 最终映射
CHINESE_TO_ENGLISH.update({
    'digital-relay-protection': 'digital-distance-protection',
    'state-space': 'state-space-method',
    'synchronous-machine': 'synchronous-machine-model',
    '电压插值法': 'voltage-interpolation',
    '电流注入法': 'current-injection',
    '状态空间平均法': 'state-space-average-method',
    '三相桥式逆变器': 'three-phase-bridge-inverter',
})

# 第七批 - 最终映射
CHINESE_TO_ENGLISH.update({
    '开关模型': 'switch-modeling',
    '电压插值模型': 'voltage-interpolation',
    '受控电流注入模型': 'current-injection',
    '简化电流注入模型': 'average-value-model',
    '模型对比与选型': 'model-comparison-selection',
    '暂态稳定性分析': 'transient-stability-analysis',
    '宽带多端口建模': 'wideband-multiport-modeling',
    '时域电磁暂态仿真': 'emt-mathematical-foundation',
    'renewable-energy-integration': 'renewable-energy-units',
})

    # ===== 高频中文断链映射 (2026-05-02 扩展) =====

# 第八批 - 高频中文断链映射 (2026-05-02 扩展)
CHINESE_TO_ENGLISH.update({
    # 计算与仿真
    '自动代码生成': 'automatic-code-generation',
    '代码生成': 'automatic-code-generation',
    '数值积分误差': 'numerical-integration-error',
    '稳态初始化': 'steady-state-initialization',
    '初始化': 'steady-state-initialization',
    '高频暂态分析': 'high-frequency-transient-analysis',
    '最小二乘法': 'least-squares-method',
    '最小二乘': 'least-squares-method',
    '高性能计算': 'high-performance-computing',
    '异构计算': 'heterogeneous-computing',
    'gpu并行加速': 'gpu-parallel-acceleration',
    'gpu加速': 'gpu-parallel-acceleration',
    '多线程并行计算': 'multithreaded-parallel-computing',
    '多线程': 'multithreaded-parallel-computing',
    '硬件加速': 'hardware-acceleration',
    '稀疏矩阵技术': 'sparse-matrix-techniques',
    '稀疏矩阵': 'sparse-matrix-techniques',
    '计算加速': 'computational-acceleration',
    '大步长仿真': 'large-timestep-simulation',
    '有限差分时域法': 'fdtd',
    'fdtd': 'fdtd',
    '时域建模': 'time-domain-modeling',
    '离散傅里叶变换': 'discrete-fourier-transform',
    'dft': 'discrete-fourier-transform',
    '双线性变换': 'bilinear-transform',
    '希尔伯特变换': 'hilbert-transform',
    '部分分式展开': 'partial-fraction-expansion',
    '诺顿等效电路': 'norton-equivalent',
    '诺顿等效': 'norton-equivalent',
    '戴维南等效模型': 'thevenin-equivalent',
    '戴维南等效': 'thevenin-equivalent',
    'dq坐标变换': 'dq-transformation',
    'dq变换': 'dq-transformation',
    'park变换': 'dq-transformation',
    '最近电平控制': 'nearest-level-control',
    'nlm': 'nearest-level-control',
    '无源性保证': 'passivity-enforcement',
    '数值拉普拉斯逆变换': 'numerical-laplace-transform-inversion',
    '机电暂态模型': 'electromechanical-modeling',
    '频变网络等值': 'fdne-model',
    '小信号稳定性分析': 'small-signal-stability-analysis',
    
    # 电力设备与建模
    '输电网络': 'transmission-network',
    '电力系统网络': 'power-system-network',
    '交流输电线路': 'ac-transmission-line',
    '网侧变流器': 'grid-side-converter',
    '网侧': 'grid-side-converter',
    '理想开关模型': 'ideal-switch-model',
    '详细开关模型': 'detailed-switch-model',
    '开关函数模型': 'switching-function',
    '磁饱和建模': 'magnetic-saturation-modeling',
    '混合建模': 'hybrid-modeling',
    '集中参数模型': 'lumped-parameter-model',
    '分布参数模型': 'distributed-parameter-model',
    '节点导纳矩阵': 'nodal-admittance-matrix',
    '节点导纳矩阵求解': 'nodal-admittance-matrix-solution',
    '伴随电路模型': 'companion-circuit',
    'rlc支路': 'rlc-branch',
    '配电变压器': 'distribution-transformer',
    '绝缘子串': 'insulator-string',
    '绝缘配合': 'insulation-coordination',
    '桥臂电抗器': 'arm-reactor',
    '交叉互联电缆': 'cross-bonded-cable',
    '地下电缆建模': 'underground-cable-modeling',
    '接地系统建模': 'grounding-system-modeling',
    '多层大地模型': 'multilayer-earth-model',
    '大地返回阻抗': 'earth-return-impedance',
    '频率相关输电线路': 'frequency-dependent-transmission-line',
    '传输线理论': 'transmission-line-theory',
    '交流滤波器': 'ac-filter',
    '光伏电站': 'pv-power-plant',
    '分布式电源': 'distributed-generation',
    '负荷': 'load-model',
    '恒功率负载': 'constant-power-load',
    '单相感应电机': 'single-phase-induction-machine',
    '双向dc-dc变换器': 'bidirectional-dc-dc-converter',
    '电力电子变换器建模': 'power-electronics-converter-modeling',
    '换流器建模': 'converter-modeling',
    '构网型控制': 'grid-forming-control',
    '故障穿越': 'fault-ride-through',
    '低压穿越': 'low-voltage-ride-through',
    'lvrt': 'low-voltage-ride-through',
    '直接接口技术': 'direct-interface-technique',
    '接口技术': 'interface-technique',
    '硬件在环-hil': 'hil-simulation',
    'hil': 'hil-simulation',
    
    # MMC/HVDC相关
    '半桥子模块-hbsm': 'half-bridge-smb',
    '半桥子模块': 'half-bridge-smb',
    'hbsm': 'half-bridge-smb',
    '全桥子模块-fbsm': 'full-bridge-smb',
    '全桥子模块': 'full-bridge-smb',
    'fbsm': 'full-bridge-smb',
    '子模块-sm': 'submodule',
    '子模块': 'submodule',
    'sm': 'submodule',
    
    # 雷电与接地
    '雷电流源': 'lightning-current-source',
    '雷击暂态分析': 'lightning-transient-analysis',
    '雷击感应电压': 'lightning-induced-voltage',
    '地电位升': 'ground-potential-rise',
    'gpr': 'ground-potential-rise',
    
    # 测试系统
    'ieee-118节点系统': 'ieee-118-bus-system',
    '交直流混合系统': 'hybrid-acdc-network',
    
    # 仿真工具
    'pscad-emtdc电磁暂态仿真': 'pscad-emtdc',
    'pscad': 'pscad-emtdc',
    '大规模系统仿真': 'large-scale-system-simulation',
})

# 第九批 - 高频中文断链映射 (2026-05-02 第二轮扩展)
CHINESE_TO_ENGLISH.update({
    # 高频中文术语
    '有限差分时域法-fdtd': 'fdtd',
    '并联电抗器': 'shunt-reactor',
    '并网变流器': 'grid-connected-converter',
    '数值积分算法': 'numerical-integration-algorithm',
    '电压源': 'voltage-source',
    '输电线路参数计算': 'transmission-line-parameter-calculation',
    '实时电磁暂态仿真': 'real-time-emt-simulation',
    'lc滤波器': 'lc-filter',
    '电磁暂态-emt-仿真': 'emt-simulation',
    '地回路阻抗计算': 'earth-return-impedance-calculation',
    '大规模电网建模': 'large-scale-grid-modeling',
    '快速仿真': 'fast-simulation',
    '理想开关': 'ideal-switch',
    '宽频建模': 'wideband-modeling',
    '阻抗稳定性分析': 'impedance-stability-analysis',
    'π型等效电路': 'pi-equivalent-circuit',
    '升压变压器': 'step-up-transformer',
    '多绕组变压器': 'multi-winding-transformer',
    '动态相量模型': 'dynamic-phasor-model',
    '频变线路建模': 'frequency-dependent-line-modeling',
    '电力电缆': 'power-cable',
    '配电网': 'distribution-network',
    '分布参数输电线路': 'distributed-parameter-transmission-line',
    '混合仿真接口': 'hybrid-simulation-interface',
    '电力电子换流器': 'power-electronics-converter',
    '模态解耦': 'modal-decoupling',
    '矢量拟合-vf': 'vector-fitting',
    '换流器': 'converter',
    '串联补偿输电线路': 'series-compensated-transmission-line',
    'gear法': 'gear-method',
    '机电暂态': 'electromechanical-transient',
    '齿轮法': 'gear-method',
    
    # 设备与建模
    '开关函数方法': 'switching-function-method',
    'gpu并行加速': 'gpu-parallel-acceleration',
    '理想开关模型': 'ideal-switch-model',
    '详细开关模型': 'detailed-switch-model',
    '数值积分误差': 'numerical-integration-error',
    '稳态初始化': 'steady-state-initialization',
    '高频暂态分析': 'high-frequency-transient-analysis',
    '最小二乘法': 'least-squares-method',
    '最小二乘': 'least-squares-method',
    '高性能计算': 'high-performance-computing',
    '异构计算': 'heterogeneous-computing',
    '多线程并行计算': 'multithreaded-parallel-computing',
    '多线程': 'multithreaded-parallel-computing',
    '硬件加速': 'hardware-acceleration',
    '稀疏矩阵技术': 'sparse-matrix-techniques',
    '稀疏矩阵': 'sparse-matrix-techniques',
    '计算加速': 'computational-acceleration',
    '大步长仿真': 'large-timestep-simulation',
    '时域建模': 'time-domain-modeling',
    '离散傅里叶变换': 'discrete-fourier-transform',
    'dft': 'discrete-fourier-transform',
    '双线性变换': 'bilinear-transform',
    '希尔伯特变换': 'hilbert-transform',
    '部分分式展开': 'partial-fraction-expansion',
    '诺顿等效电路': 'norton-equivalent',
    '诺顿等效': 'norton-equivalent',
    '戴维南等效模型': 'thevenin-equivalent',
    '戴维南等效': 'thevenin-equivalent',
    'dq坐标变换': 'dq-transformation',
    'dq变换': 'dq-transformation',
    'park变换': 'dq-transformation',
    '最近电平控制': 'nearest-level-control',
    'nlm': 'nearest-level-control',
    '无源性保证': 'passivity-enforcement',
    '数值拉普拉斯逆变换': 'numerical-laplace-transform-inversion',
    '机电暂态模型': 'electromechanical-modeling',
    '频变网络等值': 'fdne-model',
    '小信号稳定性分析': 'small-signal-stability-analysis',
    '暂态稳定': 'transient-stability',
    '暂态稳定性': 'transient-stability',
    '绝缘配合': 'insulation-coordination',
})
