#!/usr/bin/env python3
"""Add reader-facing deep review blocks to source pages.

The deep review block is a compact synthesis layer. It answers:

1. actual research need, object, challenge, and contribution;
2. proposed models, algorithms, and implementation techniques;
3. validation design, advantages, and limitations;
4. research value and reusable insight.

It is intentionally separate from the detailed extraction block generated by
deep_enrich_sources.py, so it can be regenerated without disturbing formulas,
tables, or existing page metadata.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import os
from pathlib import Path
import re
import time
from typing import Any

from llm_client import make_llm_client


ROOT = Path(__file__).resolve().parents[1]
WIKI_SOURCES = ROOT / "wiki" / "sources"
ENHANCED_DIR = ROOT / "extracted_text" / "markdown_enhanced"
MARKDOWN_DIR = ROOT / "extracted_text" / "markdown"
PDFTOTEXT_DIR = ROOT / "extracted_text" / "pdftotext"
QUALITY_REPORT = ROOT / "reports" / "wiki_quality_audit.json"
STRICT_REPORT = ROOT / "reports" / "wiki_strict_audit.json"
CHECKPOINT = ROOT / ".deep_review.json"

REVIEW_START = "<!-- deep-review:start -->"
REVIEW_END = "<!-- deep-review:end -->"


def is_inactive(content: str) -> bool:
    return "type: duplicate-source" in content or "type: out-of-scope-source" in content


def is_usable_text(text: str) -> bool:
    return len(text.strip()) >= 500


def section_text(content: str, section: str) -> str:
    match = re.search(rf"^## {re.escape(section)}\s*\n(.*?)(?=^## |\Z)", content, re.S | re.M)
    return match.group(1).strip() if match else ""


def frontmatter_value(content: str, key: str) -> str:
    match = re.search(r"^---\n(.*?)\n---", content, re.S | re.M)
    if not match:
        return ""
    field = re.search(rf"^{re.escape(key)}:\s*(.*)$", match.group(1), re.M)
    return field.group(1).strip().strip('"') if field else ""


def source_text_for(path: Path) -> str:
    candidates = [
        ENHANCED_DIR / path.name,
        MARKDOWN_DIR / path.name,
        PDFTOTEXT_DIR / f"{path.stem}.txt",
    ]
    base_stem = re.sub(r"-(?:\d+|fix)$", "", path.stem)
    if base_stem != path.stem:
        candidates.extend(
            [
                ENHANCED_DIR / f"{base_stem}.md",
                MARKDOWN_DIR / f"{base_stem}.md",
                PDFTOTEXT_DIR / f"{base_stem}.txt",
            ]
        )
    for candidate in candidates:
        if candidate.exists():
            text = candidate.read_text(encoding="utf-8", errors="ignore")
            if is_usable_text(text):
                return text
    return ""


def load_checkpoint(path: Path = CHECKPOINT) -> dict[str, list[str]]:
    if path.exists():
        data = json.loads(path.read_text(encoding="utf-8"))
        data.setdefault("done", [])
        data.setdefault("failed", [])
        return data
    return {"done": [], "failed": []}


def save_checkpoint(data: dict[str, list[str]], path: Path = CHECKPOINT) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def load_priority() -> dict[str, tuple[int, int]]:
    priority: dict[str, tuple[int, int]] = {}
    if QUALITY_REPORT.exists():
        audits = json.loads(QUALITY_REPORT.read_text(encoding="utf-8"))
        for index, item in enumerate(audits):
            if item.get("page_type") != "source":
                continue
            path = Path(item.get("path", ""))
            if path.name:
                priority[path.name] = (int(item.get("score", 100)), index)
    if STRICT_REPORT.exists():
        findings = json.loads(STRICT_REPORT.read_text(encoding="utf-8"))
        for index, item in enumerate(findings):
            if item.get("page_type") != "source":
                continue
            path = Path(item.get("path", ""))
            if path.name:
                existing = priority.get(path.name, (100, index))
                priority[path.name] = (min(existing[0], 60), index)
    return priority


def has_review(content: str) -> bool:
    return REVIEW_START in content and REVIEW_END in content


def strip_review(content: str) -> str:
    pattern = rf"\n?{re.escape(REVIEW_START)}[\s\S]*?{re.escape(REVIEW_END)}\n?"
    return re.sub(pattern, "\n", content).rstrip() + "\n"


def insert_review(content: str, block: str) -> str:
    content = strip_review(content)
    abstract_match = re.search(r"(^## 摘要\s*\n.*?)(?=^## |\Z)", content, re.S | re.M)
    marked = f"\n{REVIEW_START}\n{block.strip()}\n{REVIEW_END}\n"
    if abstract_match:
        return content[: abstract_match.end()] + marked + content[abstract_match.end() :]
    frontmatter_match = re.search(r"^---\n.*?\n---\n", content, re.S)
    if frontmatter_match:
        return content[: frontmatter_match.end()] + marked + content[frontmatter_match.end() :]
    return marked + content


def build_prompt(page_content: str, source_text: str) -> str:
    title = frontmatter_value(page_content, "title")
    authors = frontmatter_value(page_content, "authors")
    year = frontmatter_value(page_content, "year")
    journal = frontmatter_value(page_content, "journal")
    existing = "\n\n".join(
        f"## {name}\n{section_text(page_content, name)}"
        for name in ["摘要", "核心贡献", "方法细节", "仿真结果", "量化发现", "验证详情", "适用边界"]
        if section_text(page_content, name)
    )
    source_excerpt = source_text[:36000]
    return f"""你是电磁暂态(EMT)仿真领域的论文审读者。请把下面这篇source page改造成“读完能真正理解研究工作”的入口说明。

元数据：
- title: {title}
- authors: {authors}
- year: {year}
- journal/container: {journal}

当前页面已有内容：
{existing[:18000]}

论文/抽取文本证据：
{source_excerpt}

请只输出JSON，字段如下：
{{
  "need_object_challenge_contribution": "用250-450字说明：实际工程/研究需求是什么；研究对象是什么；为什么难；本文相对已有方法的创新贡献是什么。必须具体，不要写空泛的提高效率/精度。",
  "models_algorithms_implementation": "用250-500字说明：提出了什么模型、算法或实现技术；核心状态量/接口量/输入输出是什么；关键公式或计算流程在机制上起什么作用。",
  "validation_advantages_limits": "用250-500字说明：作者如何验证有效性；测试系统、工具、基线、指标是什么；优势体现在哪些方面；哪些结论没有验证或存在适用边界。",
  "value_insight_use": "用180-350字说明：这项工作提升了什么认知；能解决什么问题；适合被哪些后续页面/方法/工程场景复用；不适合被怎样外推。",
  "evidence_boundary": [
    "列出3-6条证据边界或不确定性：哪些来自原文，哪些只是据方法推断；缺少哪些关键实验/参数/场景。"
  ]
}}

硬性要求：
1. 必须紧扣原文，不得编造数值、工具、测试系统、作者没做的对比。
2. 如果原文没有给出量化数字，就明确写“原文未报告可核验的数值结果”，不要用大幅、显著、优秀替代。
3. 需要说清模型/算法“怎么工作”，不能只说“提出某模型并验证有效”。
4. 需要指出不足或边界，即使论文没有主动讨论，也要以“从验证范围看”表达。
5. 输出必须是可解析JSON，不要Markdown代码块，不要额外解释。
"""


def extract_json(text: str) -> dict[str, Any]:
    cleaned = text.strip()
    if cleaned.startswith("```json"):
        cleaned = cleaned[7:]
    if cleaned.startswith("```"):
        cleaned = cleaned[3:]
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3]
    cleaned = cleaned.strip()
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", cleaned)
        if match:
            return json.loads(match.group(0))
        raise


def render_review(data: dict[str, Any]) -> str:
    required = [
        "need_object_challenge_contribution",
        "models_algorithms_implementation",
        "validation_advantages_limits",
        "value_insight_use",
    ]
    if not all(str(data.get(key, "")).strip() for key in required):
        return ""
    lines = [
        "## 研究解读",
        "",
        "### 1. 需求、对象、挑战与贡献",
        "",
        str(data["need_object_challenge_contribution"]).strip(),
        "",
        "### 2. 模型、算法与实现技术",
        "",
        str(data["models_algorithms_implementation"]).strip(),
        "",
        "### 3. 验证、优势与不足",
        "",
        str(data["validation_advantages_limits"]).strip(),
        "",
        "### 4. 价值、认知与可复用场景",
        "",
        str(data["value_insight_use"]).strip(),
        "",
        "### 证据边界",
        "",
    ]
    boundaries = data.get("evidence_boundary", [])
    if isinstance(boundaries, str):
        boundaries = [boundaries]
    for item in boundaries:
        text = str(item).strip()
        if text:
            lines.append(f"- {text}")
    if not any(line.startswith("- ") for line in lines):
        lines.append("- 原文证据边界未充分给出；后续复核应回到PDF表图和实验设置。")
    return "\n".join(lines) + "\n"


def process_file(path: Path, llm_client: Any, force: bool, dry_run: bool) -> tuple[str, bool, str]:
    content = path.read_text(encoding="utf-8")
    if is_inactive(content):
        return path.name, True, "skipped inactive"
    if has_review(content) and not force:
        return path.name, True, "already reviewed"
    source_text = source_text_for(path)
    if not source_text:
        return path.name, False, "no extracted text"
    prompt = build_prompt(content, source_text)
    response = llm_client.complete(prompt, max_tokens=4500, temperature=0.1, timeout=180.0)
    data = extract_json(response)
    block = render_review(data)
    if not block:
        return path.name, False, "empty review block"
    if dry_run:
        return path.name, True, f"dry-run review ({len(block)} chars)"
    path.write_text(insert_review(content, block), encoding="utf-8")
    return path.name, True, f"reviewed ({len(block)} chars)"


def load_manifest(path: Path) -> list[Path]:
    files: list[Path] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        candidate = Path(line)
        if not candidate.is_absolute():
            candidate = ROOT / candidate
        files.append(candidate)
    return files


def select_files(
    limit: int,
    force: bool,
    retry_failed: bool,
    checkpoint_path: Path = CHECKPOINT,
    manifest_path: Path | None = None,
) -> list[Path]:
    checkpoint = load_checkpoint(checkpoint_path)
    if retry_failed:
        files = [WIKI_SOURCES / name for name in checkpoint.get("failed", []) if (WIKI_SOURCES / name).exists()]
    elif manifest_path:
        done = set(checkpoint.get("done", []))
        files = []
        for path in load_manifest(manifest_path):
            if not path.exists():
                continue
            content = path.read_text(encoding="utf-8")
            if is_inactive(content):
                continue
            if not force and (path.name in done or has_review(content)):
                continue
            files.append(path)
    else:
        files = []
        done = set(checkpoint.get("done", []))
        for path in WIKI_SOURCES.glob("*.md"):
            content = path.read_text(encoding="utf-8")
            if is_inactive(content):
                continue
            if not force and (path.name in done or has_review(content)):
                continue
            files.append(path)
        priority = load_priority()
        files.sort(key=lambda p: priority.get(p.name, (100, 10**9)) + (p.name,))
    return files[:limit] if limit else files


def write_report(path: Path, results: list[dict[str, Any]], elapsed_seconds: float) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "counts": {
            "items": len(results),
            "ok": sum(1 for item in results if item["ok"]),
            "failed": sum(1 for item in results if not item["ok"]),
        },
        "elapsed_seconds": round(elapsed_seconds, 3),
        "items": results,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def run(args: argparse.Namespace) -> None:
    checkpoint_path = args.checkpoint if args.checkpoint.is_absolute() else ROOT / args.checkpoint
    manifest_path = None
    if args.manifest:
        manifest_path = args.manifest if args.manifest.is_absolute() else ROOT / args.manifest

    files = select_files(args.limit, args.force, args.retry_failed, checkpoint_path, manifest_path)
    print(f"Deep review source pages: {len(files)} selected")
    if not files:
        return

    checkpoint = load_checkpoint(checkpoint_path)
    llm_client = make_llm_client(provider=args.llm_provider, model=args.model)
    start = time.time()
    completed = 0
    results: list[dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=args.concurrency) as executor:
        futures = {executor.submit(process_file, path, llm_client, args.force, args.dry_run): path.name for path in files}
        for future in as_completed(futures):
            fallback_name = futures[future]
            try:
                name, ok, message = future.result()
            except Exception as exc:  # Keep long batch runs resumable after API/socket failures.
                name, ok, message = fallback_name, False, f"{type(exc).__name__}: {exc}"
            completed += 1
            if ok:
                if not args.dry_run and name not in checkpoint["done"]:
                    checkpoint["done"].append(name)
                checkpoint["failed"] = [item for item in checkpoint["failed"] if item != name]
                print(f"[{completed}/{len(files)}] OK {name}: {message}")
            else:
                if not args.dry_run and name not in checkpoint["failed"]:
                    checkpoint["failed"].append(name)
                print(f"[{completed}/{len(files)}] FAIL {name}: {message}")
            results.append({"name": name, "ok": ok, "message": message})
            if completed % 5 == 0 and not args.dry_run:
                save_checkpoint(checkpoint, checkpoint_path)
    if not args.dry_run:
        save_checkpoint(checkpoint, checkpoint_path)
    elapsed = time.time() - start
    if args.report:
        report_path = args.report if args.report.is_absolute() else ROOT / args.report
        write_report(report_path, results, elapsed)
    print(f"Done in {elapsed / 60:.1f}m; checkpoint done={len(checkpoint['done'])}, failed={len(checkpoint['failed'])}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate reader-facing deep reviews for source pages")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--concurrency", type=int, default=4)
    parser.add_argument("--llm-provider", choices=["codex", "openai", "anthropic"], default=os.environ.get("WIKI_LLM_PROVIDER", "codex"))
    parser.add_argument("--model", default=None)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--retry-failed", action="store_true")
    parser.add_argument("--manifest", type=Path, default=None, help="Process exactly the source files listed in this manifest")
    parser.add_argument("--checkpoint", type=Path, default=CHECKPOINT, help="Checkpoint JSON path")
    parser.add_argument("--report", type=Path, default=None, help="Write per-run result report JSON")
    args = parser.parse_args()
    run(args)


if __name__ == "__main__":
    main()
